name: Branch Restrictions

on:
  pull_request:
    branches:
      - main

jobs:
  validate_source_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Validate source branch
        if: |
          github.event.pull_request.head.ref != 'develop' &&
          !startsWith(github.event.pull_request.head.ref, 'hotfix/')
        run: |
          echo "Error: Forbidden branch"
          exit 1
