name: Google Calendar Job

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  google-calendar-sync:
    runs-on: ubuntu-latest

    env:
      GOOGLE_CALENDAR_IDS: ${{ secrets.GOOGLE_CALENDAR_IDS }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0

      - name: Install dependencies
        run: uv sync

      - name: Run python
        run: uv run python main.py
